version: "3.9"
services:
  api:
    build:
      context: .
      args:
        RUN_ID: "352038f9ce0e4ea29368f96c014a314b"
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=file:/app/mlruns
